# Generated by Django 5.2.2 on 2025-06-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OfferDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("revisions", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "delivery_time_in_days",
                    models.PositiveIntegerField(blank=True, default=0),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10),
                ),
                (
                    "offer_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("standard", "Standard"),
                            ("premium", "Premium"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Detail",
                "verbose_name_plural": "Offer Details",
            },
        ),
    ]
