# Generated by Django 5.2.2 on 2025-06-10 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.CharField(default="profile_picture.jpg")),
                ("location", models.CharField(blank=True, default="", max_length=50)),
                (
                    "tel",
                    models.DecimalField(
                        blank=True, decimal_places=15, default="", max_digits=15
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "working_hours",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="auth_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
