# Generated by Django 5.2.2 on 2025-06-11 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="profile",
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("file", models.CharField(default="profile_picture.jpg")),
                ("location", models.CharField(blank=True, default="", max_length=50)),
                ("tel", models.CharField(blank=True, default="", max_length=15)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "working_hours",
                    models.CharField(blank=True, default="", max_length=50),
                ),
            ],
        ),
    ]
