# Generated by Django 5.2.2 on 2025-06-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="tel",
            field=models.CharField(blank=True, default="", max_length=15),
        ),
    ]
